# Generated by Django 3.0.6 on 2020-05-17 12:22

from django.db import migrations, models
import django.db.models.deletion
import djangocms_unitegallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_unitegallery_gallery', serialize=False, to='cms.CMSPlugin')),
                ('theme', models.CharField(choices=[('default', 'Default'), ('carousel', 'Carousel'), ('compact', 'Compact'), ('grid', 'Grid'), ('slider', 'Slider'), ('tiles', 'Tiles'), ('tilesgrid', 'Tiles grid')], default='default', max_length=20, verbose_name='Theme')),
                ('options', models.TextField(blank=True, help_text='This field allow you to pass a JSON object if you want to customize the gallery. Please consult the Unite gallery docs for a list of options.', verbose_name='Theme options')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=djangocms_unitegallery.models.get_media_path, verbose_name='Photo')),
                ('title', models.CharField(blank=True, help_text="Leave this blank if you don't want to display a title.", max_length=100, verbose_name='Title')),
                ('description', models.CharField(blank=True, help_text="Leave this blank if you don't want to display a description.", max_length=255, verbose_name='Description')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='djangocms_unitegallery.Gallery', verbose_name='Gallery')),
            ],
        ),
    ]
